import csv
import datetime
import io
import json

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, PageBreak, HRFlowable)

ACCENT = colors.HexColor("#0f766e")
DARK = colors.HexColor("#111827")


def to_csv(records):
    if not records:
        return ""
    buf = io.StringIO()
    fieldnames = []
    for r in records:
        for k in r:
            if k not in fieldnames:
                fieldnames.append(k)
    w = csv.DictWriter(buf, fieldnames=fieldnames, extrasaction="ignore")
    w.writeheader()
    for r in records:
        w.writerow({k: ("" if v is None else str(v)) for k, v in r.items()})
    return buf.getvalue()


def to_json(records):
    return json.dumps(records, indent=2, default=str)


def _esc(x):
    if isinstance(x, bool):
        x = "true" if x else "false"
    elif x is not None:
        x = str(x)
    return (x or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _render_table(rows, colw=None):
    if not rows:
        return Spacer(1, 2)
    cols = list(rows[0].keys())
    data = [[_esc(c).upper() for c in cols]]
    for r in rows:
        data.append([_esc(r.get(c)) for c in cols])
    t = Table(data, repeatRows=1, colWidths=colw)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t


def report_pdf(meta, records=None):
    """Polished analyst report: cover page + attribution verdict + evidence
    table + timeline + method notes. `meta` keys:
      title, subtitle, classification, verdict (dict), coverage, method_notes
    `records` (optional) renders as the evidence table."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=54, rightMargin=54, topMargin=54, bottomMargin=54)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("title", parent=styles["Title"], fontSize=22,
                           textColor=DARK, leading=26)
    sub = ParagraphStyle("sub", parent=styles["Heading2"], fontSize=12,
                         textColor=colors.HexColor("#4b5563"), leading=15)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=13,
                        textColor=ACCENT, spaceBefore=12, spaceAfter=4)
    verdict = ParagraphStyle("verdict", parent=styles["Normal"], fontSize=10.5, leading=14)
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=8.5,
                           textColor=colors.HexColor("#6b7280"), leading=11)
    flow = []

    # ---- cover page ----
    flow += [Spacer(1, 90),
             HRFlowable(width="100%", thickness=2, color=ACCENT),
             Spacer(1, 16),
             Paragraph(_esc(meta.get("title", "Dark Force Intelligence Report")), title),
             Spacer(1, 8),
             Paragraph(_esc(meta.get("subtitle", "Dark web threat-actor de-anonymization")), sub),
             Spacer(1, 30),
             Paragraph(f"Classification: <b>{_esc(meta.get('classification', 'UNCLASSIFIED // PUBLIC RELEASE'))}</b>", verdict),
             Spacer(1, 6),
             Paragraph(f"Date: <b>{_esc(meta.get('date') or datetime.date.today().isoformat())}</b>", verdict),
             Paragraph(f"Generated by: <b>DarkForce autonomous collection pipeline</b>", verdict),
             Paragraph(f"Database backend: <b>{_esc(meta.get('backend', 'sqlite'))}</b>", verdict),
             Spacer(1, 60)]
    if meta.get("coverage"):
        flow += [Paragraph(f"<b>Coverage</b>: {_esc(meta['coverage'])}", verdict)]
    flow.append(PageBreak())

    # ---- attribution verdict ----
    v = meta.get("verdict") or {}
    if v:
        flow += [Paragraph("Attribution Verdict", h2)]
        flow += [Paragraph(
            "Confidence: <b>%(c)s/1.00</b> &nbsp;&nbsp; Basis: <b>%(b)s</b>"
            % {"c": _esc(v.get("confidence", "0.5")), "b": _esc(v.get("basis", "stylometry + identifier overlap"))}, verdict)]
        if v.get("rationale"):
            flow += [Paragraph(_esc(v["rationale"]), verdict), Spacer(1, 6)]

    # ---- method notes ----
    notes = meta.get("method_notes") or [
        "Collection: read-only fetch of publicly served pages via the clearnet discovery APIs "
        "(Ahmia, dark.fail, ransomware.live) and Tor-restricted crawling.",
        "Entity resolution: identifier overlap (PGP keys, BTC/XMR wallets, emails, jabber, onions, "
        "reused content hashes) with weighted confidence edges.",
        "Stylometry: character n-gram authorship profiles with cosine similarity; feature "
        "explainability lists the top contributing features.",
        "Attribution is presented as analytic judgment with confidence, never as confirmed identity.",
    ]
    flow += [Paragraph("Method Notes", h2)]
    for n in notes:
        flow += [Paragraph("&bull;  " + _esc(n), verdict)]

    # ---- evidence table ----
    if records:
        flow += [Paragraph("Exhibit A - Collected Evidence", h2)]
        flow.append(_render_table(records))

    doc.build(flow)
    return buf.getvalue()


def to_pdf(records, title="Dark Force report"):
    return report_pdf({"title": title, "subtitle": "Evidence export"}, records)


def digest_pdf(meta, activity):
    """Editorial nightly digest PDF: headline stats + new sites table +
    high/critical findings + fresh alerts. `meta` mirrors report_pdf meta."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=54, rightMargin=54, topMargin=54, bottomMargin=54)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("title", parent=styles["Title"], fontSize=20,
                           textColor=DARK, leading=24)
    sub = ParagraphStyle("sub", parent=styles["Heading2"], fontSize=11,
                         textColor=colors.HexColor("#4b5563"), leading=14)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=13,
                        textColor=ACCENT, spaceBefore=12, spaceAfter=4)
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=9.5, leading=13)
    flow = [Spacer(1, 60), HRFlowable(width="100%", thickness=2, color=ACCENT),
            Spacer(1, 14),
            Paragraph(_esc(meta.get("title", "DarkForce Nightly Digest")), title),
            Spacer(1, 6),
            Paragraph(_esc(meta.get("subtitle", "24-hour collection summary")), sub),
            Spacer(1, 20),
            Paragraph("Generated by: <b>DarkForce autonomous collection pipeline</b>", body),
            Paragraph(f"Generator UTC: <b>{_esc(meta.get('date'))}</b>", body),
            Paragraph(f"Database backend: <b>{_esc(meta.get('backend', 'sqlite'))}</b>", body),
            Spacer(1, 24)]

    snap = activity.get("snapshot") or {}
    rows = [
        {"Statistic": "Sites indexed", "New 24h": activity.get("new_sites_total", 0), "Total": snap.get("sites", 0)},
        {"Statistic": "Findings", "New 24h": activity.get("new_findings_total", 0), "Total": snap.get("findings", 0)},
        {"Statistic": "Actors", "New 24h": "-", "Total": snap.get("actors", 0)},
        {"Statistic": "Identifiers", "New 24h": "-", "Total": snap.get("identifiers", 0)},
        {"Statistic": "Alerts raised", "New 24h": activity.get("new_alerts_total", 0), "Total": "-"},
    ]
    flow += [Paragraph("Snapshot", h2), _render_table(rows)]

    by_cat = sorted(activity.get("new_sites_by_category", {}).items(), key=lambda kv: -kv[1])
    if by_cat:
        flow += [Paragraph("New sites by category", h2),
                 _render_table([{"Category": c, "Sites 24h": n} for c, n in by_cat])]

    graves = activity.get("high_critical_findings", [])
    if graves:
        flow += [Paragraph("High / critical findings (24h)", h2),
                 _render_table([{"Kind": f.get("kind"), "Severity": f.get("severity"),
                                 "Site": f.get("site") or f.get("url")} for f in graves[:30]])]

    realerts = activity.get("new_alerts", [])
    if realerts:
        flow += [Paragraph("Fresh alerts (24h)", h2),
                 _render_table([{"Kind": a.get("kind"), "Title": a.get("title"),
                                 "Confidence": f"{round((a.get('confidence') or 0) * 100)}%"} for a in realerts[:30]])]

    doc.build(flow)
    return buf.getvalue()


def export(results, fmt, title="Dark Force export"):
    if fmt == "csv":
        return to_csv(results).encode("utf-8"), "text/csv", "export.csv"
    if fmt == "json":
        return to_json(results).encode("utf-8"), "application/json", "export.json"
    if fmt == "pdf":
        return to_pdf(results, title), "application/pdf", "export.pdf"
    raise ValueError(fmt)